version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:${SOFTWARE_VERSION_TAG}
    restart: always
    container_name: vaultwarden
    ports:
      - "172.17.0.1:8080:80"
      - "3012:3012"
    volumes:
      - ./data/:/data/
    environment:
      DOMAIN: https://${DOMAIN}
      ADMIN_TOKEN: ${ADMIN_PASSWORD}
      WEBSOCKET_ENABLED: 1
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_AUTH_MECHANISM: Plain
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SSL: 0
